### ISSUE TITLE
Chrme ext installed but 

### ISSUE THREAD

**Issue by kcstarr** [olsh/Feedly-Notifier#103]
when I hit the icon, it sends me to a page which says to install it. I go to the Chrome Web Store &, low&behold, it's already installed. other feedly exts work.

**Comment by olsh** [comment]
Hi @kcstarr,

Can you see articles in the popup or the extension suggests to log in?

**Comment by olsh** [comment]
I'm closing the issue out due to inactivity.
Feel free to reopen the issue.
