### ISSUE TITLE
after standby many times, no RSS is shown

### ISSUE THREAD

**Issue by simonmadsen** [olsh/Feedly-Notifier#104]
it just says no unread articles in the chrome feedly extension after many times standby several days and wake up computer,
consistent issue,
after restart of chrome they show again,,,

**Comment by olsh** [comment]
Hi @simonmadsen 
There are any errors in the console on the background page?

**Comment by simonmadsen** [comment]
You mean the website that's open?

Didn't check the console but it happened on all websites.
Don't think that's related.
Maybe I misunderstood something.
But the feeds don't load after some time that's for sure.
I think because if standby
________________________________

**Comment by olsh** [comment]
> You mean the website that's open?

Sorry, I meant the extension background page and its console.
In order to open it, you have to go `chrome://extensions/` page, turn on `Developer mode` and click `background page` link. Please see the screenshot,

![screenshot_092517_025241_pm](https://user-images.githubusercontent.com/3613592/30807152-4a04d87e-a201-11e7-955b-3c9c681ef1bd.jpg)

**Comment by simonmadsen** [comment]
OK so I'm a developer now : )


NP, see the screen below and let me know if you need more


[cid:c29351c4-bcf5-479b-a479-e78dd8a7493a]

________________________________

**Comment by olsh** [comment]
> OK so I'm a developer now : )
You're welcome)

It seems like the screen wasn't attached.

**Comment by simonmadsen** [comment]
please see attached


https://www.youtube.com/watch?v=Vhh_GeBPOhs


________________________________

**Comment by olsh** [comment]
Watched the video 3 times, but still, have no idea why this bug happens.

**Comment by simonmadsen** [comment]
Didn't you see the picture attached
Basically it's a 401 authentication error
________________________________

**Comment by olsh** [comment]
I didn't see the image, attach it on GitHub please.

**Comment by simonmadsen** [comment]
hi Oleg, maybe you can open this link:

https://drive.google.com/file/d/0B6EWkYARgwFURjF6cmpHMWY5NTg/view?usp=sharing

________________________________

**Comment by simonmadsen** [comment]
perhaps just due to me being logged out, but it happens too often, like after a week,


perhaps prolong the time I stay logged in though perhaps you cannot control that, probably it is an feedly.com setting,


perhaps I can edit the cookie to stay logged in longer,


or there is also another problem,


sometimes as I remember just restarting chrome fixes it,


anyway thanks

________________________________

**Comment by olsh** [comment]
This issue probably related to #58, will try to investigate.

**Comment by simonmadsen** [comment]
ok maybe, I will try to give more info on how regularly it happens etc.


thanks for assisting and great work

________________________________

**Comment by 6yPaTuHo** [comment]
Приветствую!
У меня тоже перестало обновляться расширение в браузере Chrome и FireFox (все версии последние).
На самом сайте feedly.com все показывается ок.
С чем это может быть связано и как починить?
Спасибо.

**Comment by Kougeru** [comment]
Having this same issue lately. Thing says "Failed to load resource: the server responded with a status of 401 ()"
"Unable to update feeds"
"Unable to load counters."
"Failed to load resource: the server responded with a status of 401 ()"
"{"errorCode":401, "errorId":"ap7int-sv2.2017102420.2951754", "errorMessage":"must provide authorization token"}"

**Comment by olsh** [comment]
@Kougeru thanks for the info, will investigate this.
Have you tried to re-login?

**Comment by Kougeru** [comment]
Yes. Re logging fixed the issue for a few hours but the issue comes back. I only started having this issue on October 24th.

**Comment by olsh** [comment]
@Kougeru could you please check if the auth token was passed to the failed requests?

**Comment by olsh** [comment]
Tried to solve the issue in 2.15.7, could you please try it and let me know if the issue is fixed?

**Comment by simonmadsen** [comment]
I will let you know if I experience it again in the coming weeks
________________________________

**Comment by simonmadsen** [comment]
I see some looks different, which I think is good,


if you don't hear from me again, then it's fixed,

________________________________

**Comment by olsh** [comment]
I'm closing out the issue, feel free to reopen it if the bug wasn't fixed.

**Comment by simonmadsen** [comment]
Seems better.

Thanks!

________________________________
