### ISSUE TITLE
Request: add option to save for later read

### ISSUE THREAD

**Issue by zuber1979** [olsh/Feedly-Notifier#105]
I would love to have icon to save for later read on the list of articles.

**Comment by olsh** [comment]
Hi @zuber1979,

This feature already exists. Please check `Ability to save feeds`.

**Comment by zuber1979** [comment]
Thanks, I didn't see that option. Your add-on rocks!

**Comment by olsh** [comment]
Thanks @zuber1979!

I'm closing out the issue if you don't mind.
