### ISSUE TITLE
Auto Refresh?

### ISSUE THREAD

**Issue by livejamie** [olsh/Feedly-Notifier#107]
Would it be possible to have this addon automatically poll or refresh the feeds so I don't have to manually do that throughout the day?

**Comment by olsh** [comment]
Well, the extension already does this. You can see the interval on the options page.

**Comment by livejamie** [comment]
So I get a desktop notification that I have 12 new articles and the icon changes, but the page doesn't refresh. It says "Well done! You're all caught up."

![image](https://user-images.githubusercontent.com/49513/32018804-a73a8b32-b990-11e7-8f0b-499803102d79.png)

It would be awesome if the extension detected new content that it would refresh the page so the articles appear. Or if it could detect that it is in the background and it does that.

Also, what is "Background mode?"

**Comment by olsh** [comment]
> It would be awesome if the extension detected new content that it would refresh the page so the articles appear.

Got it. I suppose this is the responsibility of feedly.com site.

> Also, what is "Background mode?"

It the option is enabled, the extension will work even if you close Chrome (check new feeds and show desktop notifications). You'll see the extension icon in the tray.
