### ISSUE TITLE
 the extension interface is not displayed

### ISSUE THREAD

**Issue by GATOQSECOMIO** [olsh/Feedly-Notifier#109]
After the update (2.15.6), I click on the icon and the content is not displayed.
The extension remains constantly loading and I can't log in.
I have re-installed the extension but it does not solve the issue.

![2017-10-28 06_04_05-developer tools - chrome-extension___egikgfbhipinieabdmcpigejkaomgjgb_background](https://user-images.githubusercontent.com/19736343/32131101-071a433c-bba6-11e7-94c5-1e3b997f2c08.png)

INFO: W7x64 SP1 // Slimjet x64 v16beta & Slimjet x64 15.1.0

I'm sorry for my poor English.  :)

**Comment by olsh** [comment]
Hi @GATOQSECOMIO!

Thanks for letting us know, we'll investigate.

**Comment by olsh** [comment]
@GATOQSECOMIO,
Please try 2.15.7 and let me know if it solves the issue.

**Comment by GATOQSECOMIO** [comment]
@olsh 

> Please try 2.15.7 and let me know if it solves the issue.

Nice ! now works perfectly :)

**Comment by olsh** [comment]
Thanks for your help! 👍
