### ISSUE TITLE
Problem with the icon

### ISSUE THREAD

**Issue by IllusioMan** [olsh/Feedly-Notifier#112]
Hello, olsh. How are you?
I'm here to report an annoying bug that begun some days ago.
The icon isn't updating automatically anymore. I need to click to appear the counter too, then to see the messages. Please, fix this.

**Comment by olsh** [comment]
Hi @IllusioMan,

Thanks for letting me know, will fix it today.

**Comment by olsh** [comment]
@IllusioMan,
just uploaded 2.15.8 version, it'll be available in few minutes, please let me know if the bug still exists.

**Comment by IllusioMan** [comment]
I update but still having problems...
The counter still doesn't update automatically and now, i need to click, read and refresh =(

**Comment by IllusioMan** [comment]
Olsh, i have news.
The counter is ok now. But the problem is about the Read. If i click on the icon of an eye or Mark all as read are not working. I need to refresh to read and change the counter O_O

**Comment by IllusioMan** [comment]
It's working!!! Nice and clear. Thanks.

**Comment by olsh** [comment]
Good to hear, thanks!
