### ISSUE TITLE
Works incorrectly in Firefox 61

### ISSUE THREAD

**Issue by zuber1979** [olsh/Feedly-Notifier#126]
- does update until clicked
- does not clear saved, when unclicked

**Comment by olsh** [comment]
Hi @zuber1979,

Can't reproduce on Windows 10.
Could you please check if there are errors in the FF console?

**Comment by wrooot** [comment]
Works as intended for me also, Win7.

**Comment by olsh** [comment]
Thanks, guys!
Closing this issue then, feel free to reopen it.

**Comment by nugend** [comment]
@olsh I'm having this issue on FF 61.0.2

I tend to leave my browser open for a week at a time. Might be some sort of timer issue?

**Comment by olsh** [comment]
Hi, @nugend!

Well, probably it's a timer issue, but sadly I can't reproduce it :(
If this happens again, could you please check console errors?
