### ISSUE TITLE
Donate button doesn't work

### ISSUE THREAD

**Issue by wrooot** [olsh/Feedly-Notifier#127]
Well, not a critical bug :) But if i press on Donate, it just goes to Paypal Home page. Maybe you should change the link to just https://www.paypal.me/feedlynotifier

**Comment by wrooot** [comment]
So, i see you have removed the donate button. Is https://www.paypal.me/feedlynotifier still valid for donations? :)

**Comment by olsh** [comment]
Hi @wrooot,

The link is invalid. I no more accept donations. 

I want to say a big thank you to all contributors who supported the project. All the money was spent on domain name and server for favicons (which you see in the extension popup).

**Comment by wrooot** [comment]
I see. Thanks for providing this useful tool. Hope it will live on and keep improving.
