### ISSUE TITLE
Do not show popup after closing last article

### ISSUE THREAD

**Issue by wrooot** [olsh/Feedly-Notifier#128]
I have "Force update feeds on popup open" disabled. When i make last article as read in the popup it still pops, runs the update and then shows the "No unread articles" in there. It would be nice to have an option to disable that last check. For me it is enough just to have a time interval and i don't need it to update that often and that last popup is distracting.

**Comment by olsh** [comment]
Hi @wrooot,

Thanks for the suggestion! 👍 
What is the desired behavior then?

**Comment by wrooot** [comment]
After i click on a link of a last article or hide last article it could just collapse and close.

**Comment by olsh** [comment]
Makes sense, and if you open the popup again it'll load new articles?

**Comment by wrooot** [comment]
Yeah, if i press it myself, even if it doesn't show a number of unread articles, i guess it should reload then. Although, personally i would only press it to go to Feedly website. As i don't often do that, i don't have strong preference there.

**Comment by olsh** [comment]
The feature is implemented in e9355490f0f7d19880b63b9bd04af360a8140ae3 and will be available in the next version.
Thanks for the suggestion 👍
