### ISSUE TITLE
Sync settings

### ISSUE THREAD

**Issue by ThiefMaster** [olsh/Feedly-Notifier#136]
At least in Firefox, the settings of the extension are not synced via Firefox Sync. It would be nice if that changed!

**Comment by akaSybe** [comment]
Current version uses Sync Storage for Firefox. 

This kind of storage doesn't support sync: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local

We need to investigate if Firefox last versions support sync storage

**Comment by marczellm** [comment]
They do.
