### ISSUE TITLE
Settings not working in ff 63.0.3

### ISSUE THREAD

**Issue by fd2012** [olsh/Feedly-Notifier#137]
There is no option to change the settings:
![feedlyext](https://user-images.githubusercontent.com/2177845/49567622-90537300-f92e-11e8-98a5-84c8bd99d867.png)

**Comment by akaSybe** [comment]
could you please specify browser & OS versions?

**Comment by fd2012** [comment]
Firefox 63.0.3 (64 bit), Windows 10 Pro (64 bit)

**Comment by akaSybe** [comment]
I'll check it tonight

**Comment by fd2012** [comment]
After closing and starting Firefox all checkboxes are there. Thank you.
