### ISSUE TITLE
Add dark theme support on upcoming Chrome v74

### ISSUE THREAD

**Issue by Kenya-West** [olsh/Feedly-Notifier#141]
Chrome v74 (which will hit the market in April) will introduce dark theme on the browser's UI.
Is there any API to detect dark theme switch to enable dark interface on the extension?

**Comment by akaSybe** [comment]
we are going to completely redesign extension soon, so, we will take this one into account when developing

**Comment by olsh** [comment]
Fixed in #165 
The update will be published to the store soon.
