### ISSUE TITLE
Popup width setting no longer applies - Firefox 66

### ISSUE THREAD

**Issue by gwolf2u** [olsh/Feedly-Notifier#142]
Setting for popup width no longer gets applied for Firefox after updating to 2.20.0

Edit:
Reverting to 2.19.0 "fixes" it

**Comment by franco999** [comment]
Me too.. Firefox Quantum v65.0 in Linux Mint 19.1

**Comment by olsh** [comment]
Can't reproduce it with Firefox 65.0.1 on Windows 10.
Have you tried to resave the settings?

**Comment by gwolf2u** [comment]
yes, even removed extension and readded

**Comment by gwolf2u** [comment]
My settings if it matters
![capture](https://user-images.githubusercontent.com/877292/52916451-43a1f600-32e8-11e9-86bc-3b016bad1aad.PNG)

**Comment by olsh** [comment]
@gwolf2u which OS are you using?
Are you using Firefox Sync?

**Comment by gwolf2u** [comment]
Windows 10 x64 updated to latest
And yes using ff sync

**Comment by franco999** [comment]
I'm back to version 2.19 and it works well for me.

I have ff sync enabled as well.

**Comment by olsh** [comment]
Well, I manage to reproduce the problem, will fix it soon.

**Comment by olsh** [comment]
The issue was fixed in 2.21.0

Thanks!
