### ISSUE TITLE
Stopped working in Waterfox, doesn't open pop-up

### ISSUE THREAD

**Issue by plisskenrd** [olsh/Feedly-Notifier#146]
Add-on was working fine then suddenly stopped working two days ago, won't open pop-up no more, just stalls loading, same thing with sidebar...

![preview](https://i.imgur.com/jnF5tGrm.jpg)  ![preview](https://i.imgur.com/ue9yKVQ.png)

**Comment by Boournz** [comment]
Same issue here. Only solution is to downgrade to v2.19 for now.

**Comment by olsh** [comment]
Waterfox is based on a pretty old version of Firefox, which doesn't support some sidebar APIs, fixed that in 2.21.2
Please note, that the extension looks even uglier in the sidebar that in the popup :) 
Because we can't use some hacks which relies on the new sidebar API.
