### ISSUE TITLE
Decrease the Interval Period

### ISSUE THREAD

**Issue by Mioni** [olsh/Feedly-Notifier#148]
First I love its extension! 🎉 
Could not you cut the interval by 5 min? or 1 min?

Thank you!

**Comment by olsh** [comment]
I'd like to do that.
And it's pretty easy to do https://github.com/olsh/Feedly-Notifier/blob/master/src/scripts/core.js#L51

But Feedly team doesn't allow to set the interval lower than 10 minutes, so I can't do that.
