### ISSUE TITLE
No Favorite category?

### ISSUE THREAD

**Issue by lorthirk** [olsh/Feedly-Notifier#151]
Hi,

I'd like to have the extension only notify for feeds in the Favorite category; however, such category is not available in the list. Am I missing something, or it needs to be implemented? I guess it should be hardcoded in someway, since it's provided by Feedly itself

**Comment by olsh** [comment]
Hi @lorthirk 

Well, I've never heard about the category before. According to the documentation, it's `user/:userId/category/global.must`.
https://developer.feedly.com/cloud/#global-resource-ids

It's nice to have feature I think.

**Comment by olsh** [comment]
The feature is implemented in 2.23.0 version.
Thank you for the suggestion 👍
