### ISSUE TITLE
Unread counter shown without items

### ISSUE THREAD

**Issue by AGlezB** [olsh/Feedly-Notifier#153]
Version: 2.22.2 on Firefox 60.8.0esr (64-bit)

The counter and the list seem bo out of sync:

![20190812-125018-000986 - Feedly](https://user-images.githubusercontent.com/12277525/62882521-0c912800-bd00-11e9-8aae-c27e91ca7fc4.png)

**Comment by AGlezB** [comment]
And more:
![image](https://user-images.githubusercontent.com/12277525/62883220-8970d180-bd01-11e9-93d9-7b55e2abbcb5.png)

**Comment by olsh** [comment]
Hi @AGlezB ,

Can you please check the console logs `ctrl + shift + J`? Also, how many unread items you see on feedly.com?

**Comment by AGlezB** [comment]
At this time I'm seeing 9.

![image](https://user-images.githubusercontent.com/12277525/62901007-afaa6780-bd29-11e9-8e4e-3a6325a4d752.png)

```
17:48:58.486 error occurred while processing 'sources: TypeError: can't access dead object
Stack: createNonSourceMappedActor@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:312:1
createSourceActors/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:400:19
Line: 312, column: 1 1 main.js:1624
	_unknownError resource://devtools/server/main.js:1624:5
	_queueResponse/responsePromise< resource://devtools/server/main.js:1650:25

```
It seems the fetching the counter is working but fetching the list is not.

**Comment by olsh** [comment]
Could you please expand the error?

**Comment by AGlezB** [comment]
![image](https://user-images.githubusercontent.com/12277525/62901276-5c84e480-bd2a-11e9-8be7-9318c09b44e4.png)

**Comment by olsh** [comment]
Thanks, will try to reproduce this tomorrow.
Have you tried to restart the browser or test the plugin on [a clean profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_creating-a-profile)?

**Comment by AGlezB** [comment]
Yes to all:

- Restart browser
- Restart PC
- Use a new --clean-- profile.
- Disable AV

**Comment by AGlezB** [comment]
@olsh This will be a lot easier if I just give you a login for my feeds. Let me know if you want it.

**Comment by AGlezB** [comment]
It seems `http://www.tftcentral.co.uk/blog/feed/` is the one causing the issues.

**Comment by olsh** [comment]
Hmm, unable to reproduce the issues, tried FF 60.8.0esr, FF 68.0.1, Chrome 76.0.3809.100 all browsers 64bit.
Used a test Feedly account with the feed.

**Comment by AGlezB** [comment]
Me neither.  I guess they fixed the feed.
Next time I'll make sure to save the XML and the JSON responses.
Thanks.
