### ISSUE TITLE
Last article is not removed on read

### ISSUE THREAD

**Issue by wrooot** [olsh/Feedly-Notifier#157]
Related to https://github.com/olsh/Feedly-Notifier/issues/128

I didn't realize at first there was a new setting for this (should have looked at the changed code). And it works, but there is a bug. When i open the last article, the popup does go away, but it doesn't update the read count and still shows 1 unread and the same article in the popup, although on Feedly side all articles show as read. It only goes away if i hit refresh in popup window.

**Comment by olsh** [comment]
Could you please specify your browser version?

**Comment by wrooot** [comment]
70.0.1

**Comment by olsh** [comment]
I managed to reproduce the issue. It seems like it affects only FF.
I just uploaded version 2.24.2 to [AMO](https://addons.mozilla.org/en-US/firefox/addon/feedly-notifier/), could you please test it when it will be approved?

**Comment by wrooot** [comment]
2.42.2 fixed this
