### ISSUE TITLE
Feedly Notifier Problem

### ISSUE THREAD

**Issue by oren64** [olsh/Feedly-Notifier#159]
Hi

I have a problem showing articles in Feedly Notifier in Firefox.
I delete my Feedly account and open a new account, and now Feedly Notifier not showing articles, like the account is not synced with Feedly Notifier.
It shows "No unread articles", and in the optiones it no showing the feeds collection name checkbox.

Thanks

**Comment by oren64** [comment]
I reinstall Firefox and now it's works ok.

**Comment by olsh** [comment]
Hi @oren64,

Thank you for the feedback! Can we close this issue?
