### ISSUE TITLE
Sound notifications

### ISSUE THREAD

**Issue by s-kaczmarek** [olsh/Feedly-Notifier#160]
That would be nice if I could decide to have sound notifications or not. I don't see any option to turn them off in settings.

**Comment by olsh** [comment]
Hi @s-kaczmarek,

Could you please specify which browser are you using?

**Comment by s-kaczmarek** [comment]
sure, firefox

niedz., 16 lut 2020 o 09:36 Oleg Shevchenko <notifications@github.com>
napisał(a):

**Comment by olsh** [comment]
Does `Play alert sound on new feeds` option work for you?
![image](https://user-images.githubusercontent.com/3613592/74634976-15165f80-5176-11ea-8a8d-2bc40902afad.png)

**Comment by s-kaczmarek** [comment]
No, when I right click on feedly icon on my address bar I only see "Remove
from Address Bar" and "Manage Extension" after clicking on "Manage
Extension" it redirects me to plugin setting, that look like this:
[image: 20200217-205638-.png]


pon., 17 lut 2020 o 09:10 Oleg Shevchenko <notifications@github.com>
napisał(a):

**Comment by olsh** [comment]
You can open the extension's options by this URL.
`moz-extension://0015e651-27f4-4f2e-8015-bacca1e7301c/options.html` or clicking on `Options` on the extensions management page
![image](https://user-images.githubusercontent.com/3613592/74685034-6823fd00-51de-11ea-8e27-bd618b3a60d7.png)

**Comment by olsh** [comment]
Closed due to inactivity, feel free to reopen the issue.
