### ISSUE TITLE
In firefox, no news was retreived

### ISSUE THREAD

**Issue by Ducatel** [olsh/Feedly-Notifier#161]
**Describe the bug**

On Firefox, there is no news retrieved and display in the addin.

![image](https://user-images.githubusercontent.com/1184332/77738384-09894480-7010-11ea-8e4b-fb508176c2a1.png)

**To Reproduce**
Steps to reproduce the behavior: (Like on the image)
1. Open the extension by clicking on it 
2. Check there is no news listed
3. Click on the link to open feedly website
4. Check there is news available

**Expected behavior**
 Should list news :D

**Desktop (please complete the following information):**
 - OS: Windows 10 (1803)
 - Browser Firefox 
 - Version 74.0

Thanks for your work ;)

**Comment by olsh** [comment]
Hi @Ducatel 

Thanks for the report.

Sadly, I can't reproduce this.

Ensure that you are using the same user in the extension and on the site, you can view the current user on the page.
`moz-extension://591f6b7a-7259-4965-b48f-2715b3023ee1/options.html`

If you OK with developer tools, you can inspect the extension on the page. Please check the `Console` tab for errors.
`about:debugging#/runtime/this-firefox`

**Comment by Ducatel** [comment]
Ok, I just deconnect/reconnect my account and it's working ....

So Thanks 👍 

Ps: For me the option page is `moz-extension://9f601241-5e67-46e0-b665-156d86c5c6e5/options.html`
