### ISSUE TITLE
Can't load favicons of feed sites

### ISSUE THREAD

**Issue by wrooot** [olsh/Feedly-Notifier#163]
**Describe the bug**
Started a day ago. Feedly Notifier can't load favicons of sites in the list. Not sure if this is some change on Feedly size. I haven't updated or changed anything in these two days i think.

**To Reproduce**
1. Open the list of new articles by pressing Feedly Notifier icon.
2. Wait for ~10 seconds while it tries to load the icons.
3. It shows a placeholder broken image icon.

**Expected behavior**
It should be loading icons as it did a few days ago.

**Screenshots**
![image](https://user-images.githubusercontent.com/7195609/79302184-4a2ffb80-7ef4-11ea-8b29-93e1c5e15c61.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro x64
 - Browser: Mozilla Firefox x64
 - Version 75.0

**Comment by olsh** [comment]
Thanks for the reporting, my icon server went down.

Fixed now.

**Comment by wrooot** [comment]
I didn't know there is a server for the icons. Was it necessary to implement this way?

**Comment by olsh** [comment]
Well, there are two reasons why I set up a custom server for icons:

* Feedly uses google service for getting icon, and it doesn't work on some domains, here is an example 
Google: https://www.google.com/s2/favicons?domain=github.com&alt=feed
Custom: https://i.olsh.me/icon?url=https://github.com&size=16..64..300&fallback_icon_url=https://www.google.com/s2/favicons?domain=https://github.com&alt=feed

* The second reason, the google service generates icons in low resolution 16x16, and these favicons look not pretty well on desktop notifications, the custom server tries to fetch icon with 64x64 resolution.

If you know alternatives, let me know.
