### ISSUE TITLE
Feature Request : Custom notification sound

### ISSUE THREAD

**Issue by whereisr0da** [olsh/Feedly-Notifier#164]
Hi, everything is in the title.

The ability to set a path to an MP3 file used as notification sound.

Thank you.

(wrong label sorry)

**Comment by whereisr0da** [comment]
Ok, thanks a lot :)

**Comment by Xebtria** [comment]
I would like to disable the sound entirely, not just set a custom mp3

**Comment by olsh** [comment]
@Xebtria, there is an option for this.
- [ ] `Play alert sound on new feeds`

Does it work for you?

**Comment by Xebtria** [comment]
@olsh 
I at first wanted to say that I don't have such an option:

https://i.imgur.com/bmlUPjL.png
https://i.imgur.com/DhCxNrO.png
https://i.imgur.com/OBwLclf.png

because in the ~5 hours I was using this extension I did not find the options, but I did now: https://i.imgur.com/HxDI3UI.png
seems like I was blind, it is working now, sorry for the inconvenience

**Comment by Gabarito007** [comment]
Where is the sound file?
I had searched under entire Firefox profile folder, but I couldn't find it.
Sound is too loud and I'd like just to change it for another one.

So...

...where is the sound file?

Txs

**Comment by olsh** [comment]
Hi @Gabarito007 
The file is here https://github.com/olsh/Feedly-Notifier/tree/master/src/sound 
and here is the code that plays it
https://github.com/olsh/Feedly-Notifier/blob/master/src/scripts/core.js#L396-L400

I'm not sure if FF unpacks extensions.

**Comment by Gabarito007** [comment]
Thank you, for your reply, olsh.

But I mean "where is the sound file" **on my computer**.
I say that because I may change it for another sound filme, not too loud than this.

There is no "alert.mp3" on my machine.
But I can hear it at each new feedly notify.

**Comment by olsh** [comment]
I believe that FF stores extensions here for windows.
`C:\Users\olsh\AppData\Roaming\Mozilla\Firefox\Profiles\yltzgf2j.default-1481210500319-1595066975366\extensions\jid1-BOjn8b0IM7kH2w@jetpack.xpi`

Where `olsh` is my OS username and `yltzgf2j.default-1481210500319-1595066975366` is my FF profile.
`jid1-BOjn8b0IM7kH2w@jetpack.xpi` is the extension file. I'm not sure if FF unpacks it on disk somewhere. Maybe FF unpacks it only in memory.

**Comment by Gabarito007** [comment]
I could find the extension. And it has, in fact, "alert.mp3" inside xpi file.
But it ruin my plans to change the sound of the file...

**Comment by Gabarito007** [comment]
Hey!

I had an idea!

I unpacked xpi file and overwritten original alert.mp3 with a lower sound and packed it again.
FF accept my modified xpi file and now I'm waiting the next notify to check if my changes work.

🙂

**Comment by Gabarito007** [comment]
> 
> 
> Hey!
> 
> I had an idea!
> 
> I unpacked xpi file and overwritten original "alert.mp3" with a lower sound, and packed it again. FF accepted my modified xpi file and, now, I'm waiting the next notify to check if my change works.
> 
> slightly_smiling_face


---------------------

Success!

I can change and/or edit file "alert.mp3" to fill my purposes.

Thank you!

😀😀😀

**Comment by wolfpurplemoon** [comment]
Thanks @Gabarito007 for detailing your steps, I can't seem to replicate them myself without corrupting the add on and having to reinstall, but I'm not even sure why this add on needs such a disruptive sound that doesn't have any options to toggle it off, anyone know a feedly add on that doesn't have a sound?

**Comment by olsh** [comment]
Hey @wolfpurplemoon 
The extension actually has such an options, please check this
https://github.com/olsh/Feedly-Notifier/issues/172
and this
https://github.com/olsh/Feedly-Notifier/issues/164#issuecomment-650726758

**Comment by wolfpurplemoon** [comment]
thanks @olsh I've never used an add on that hid its options like that, thanks for pointing to it, it was very hard to find

**Comment by Gabarito007** [comment]
I'd like to say that my old solution, to extract alert.mp3 and lower its volume, doesn't work...
After edit the sound and pack it again to a xpi file, Firefox says that the file was tampered and refuses to accept it.

So, the previous question remains: how to have a notification sound **not too loud**?

**Comment by olsh** [comment]
> I'd like to say that my old solution, to extract alert.mp3 and lower its volume, doesn't work...

I probably add `volume` parameter in the next version. 
Also, if you know some nice and free-to-use sounds, please let me know. Probably we can just add an option to choose a notification sound from a couple of sounds.

**Comment by Gabarito007** [comment]
Great!

Thank you for your prompt response.

Here, you get a lot of free use sounds.
https://notificationsounds.com/

And the tip about a volume slider is very good too.

**Comment by olsh** [comment]
I've added the ability to change the notification sound and select a sound from a predefined list (let me know if you want to add a specific sound to the collection).
These features are available in the 2.29.0 version.

Thanks 💯
