### ISSUE TITLE
Increase "Max number of feeds in the popup" to higher than 60

### ISSUE THREAD

**Issue by RejZoRSheep** [olsh/Feedly-Notifier#169]
Is there a particular reason it's limited to maximum 60 entries? I sometimes have over 150 entries and when I have time I comb through them in a popup and check the content that interests me and discard the rest. However, I can't do it from oldest to newest so I'm checking them chronologically, but have to instead go from newest to oldest and as I'm removing them, older ones show up in the popup. Why not just allow whatever number of feeds I want with top limit being something like 250 or even 500 ? I know it's a silly value, but this way user can tailor it the way they want it. And if that means 500 feeds, then so be it. Unless there is some technical reason not to allow that. Would help me greatly if this limit could be higher.

You can keep the default value to whatever it is now, but just increase the maximum number from 60 to something significantly higher. If possible of course. Would greatly appreciate that.

**Comment by olsh** [comment]
Well, this is just an artificial limitation that can be easily removed. 
I believe that I introduced the limit to avoid slow rendering in the popup, but I'm not sure.

Feedly API allows fetching more than 60 entries 

> count
> Optional integer number of entries to return. default is 20. max is 1,000 for feeds and categories, 500 for tags.

https://developer.feedly.com/v3/streams/

**Comment by olsh** [comment]
Fixed in 1db2037823da7fd22ca4d59aee5d22ada1876f3f
