### ISSUE TITLE
Where are the settings in Firefox?

### ISSUE THREAD

**Issue by ovidiuav** [olsh/Feedly-Notifier#172]
This might sound dumb, but for the life of me I can't find the settings for the Firefox version. I'm reading about all these features in the add-on description but I don't see any way to make use of them (e.g. ability to filter feeds by category in the popup).

Some help would be greatly appreciated.

**Comment by olsh** [comment]
Hi @ovidiuav 

Here they are
![image](https://user-images.githubusercontent.com/3613592/94555311-11969b00-0264-11eb-849b-a12e5e4934c5.png)

**Comment by ovidiuav** [comment]
Doh!

Thank you!
