### ISSUE TITLE
No Reddit Feeds

### ISSUE THREAD

**Issue by tjesp** [olsh/Feedly-Notifier#173]
I just updated Feedly to Feedly Pro+ in order to get access to Reddit and Twitter feeds. I have added a couple of reddit feeds and they appear fine with unread messages on the Feedly website.

I can't make them appear in this extension on Microsoft Edge in OS X. (latest version of everything). I have tried the refresh button in the extension as well and the reddit feeds are not added.

**Desktop (please complete the following information):**
 
Mac OS X High Sierra latest updates (I have a Macbook Pro 2011 and its the latest supported OS)
Microsoft Edge latest update (non beta)
Feedly Notifier latest version.

**Comment by olsh** [comment]
Hi @tjesp,

I don't have a Pro subscription, so I can't test the feature.
PRs are welcome.

**Comment by tjesp** [comment]
Just letting you know that reddit feeds were working fine. After setting up the pro+ subscription I removed this extension and reinstalled and restarted the browser and suddenly it seemed to work.

**Comment by olsh** [comment]
Thanks @tjesp ! 👍
