### ISSUE TITLE
Popup body/content max-height too low when page zoom is in use

### ISSUE THREAD

**Issue by pullasuti** [olsh/Feedly-Notifier#179]
If default page zoom in Chrome settings is set to over 100%, the content of the notifier overflows and gets two scrollbars. 

**Steps to reproduce the behavior:**
1. Go to Chrome -> Settings -> Appearance 
2. Select 'Page zoom' higher than 100%
3. Set max number of feeds to more than 6 in Feedly Notifier
3. Open Feedly notifier popup
4. See too many scrollbars

**Expected behavior**
No double scrollbars. The static max-height in styles for popup-body and popup-content should be configurable/more responsive. 600px causes issue. 

**Screenshots**
 ![image](https://user-images.githubusercontent.com/29338403/110201540-4985b800-7e6c-11eb-8911-2472324a99e9.png)

**Desktop (please complete the following information):**
 - OS: Pop_Os 20.10
 - Chrome
 - Version 89

**Comment by olsh** [comment]
Hi guys, I saw the PR. Sadly I can't test it right now because I can't reproduce the issue on my laptop (macOS).
I'll try to test it soon when I get my Windows PC.
