### ISSUE TITLE
[BUG] In version 2.25.6, "mark as read" doesn't work anymore

### ISSUE THREAD

**Issue by turbare** [olsh/Feedly-Notifier#182]
[bug]In the 2.25.6 version, mark as read doesn't work; neither clicking mark as read nor clicking the actual feed item.
Started happening today 16.03.2021

**Comment by protoz** [comment]
I came here to report the same thing.  I have to manually refresh to clear the feed.
Version: 2.25.6.  The Chrome store does not seem to have 2.25.7 (current release)

**Comment by RichDG** [comment]
Same issue in 2.25.7 (firefox)

**Comment by Kenya-West** [comment]
Can confirm, the same for Microsoft Edge

**Comment by elhennig** [comment]
Same here after Firefox update to 86.0.1

**Comment by olsh** [comment]
Hi guys,

I can't reproduce the issue on Chrome 89.0.4389.90 and Firefox 86.0.1 on Windows.

Could you please describe the bug in more detail?
What happens after clicking on the icon? Are there any errors in the console?

**Comment by Theyssen** [comment]
I have the same issue
Chrome 89.0.4389.90
Feedly notifier 2.25.6

1. Click notifier extension icon
2. Click mark all as read icon
3. The feed reloads but same content from before is visible and counter does not decrease

**Comment by RichDG** [comment]
Theyssen has described the issue perfectly. 

The only solution I have found is to literally re-start the browser after the feed reloads. Doing that clears the marked as read feeds and allows the next batch of feeds to be seen.

**Comment by elhennig** [comment]
> The only solution I have found is to literally re-start the browser after the feed reloads. Doing that clears the marked as read feeds and allows the next batch of feeds to be seen.

One workaround is to open the feedly website and mark the articles as read there.

**Comment by RichDG** [comment]
Without having done anything it appears the issue has gone. Possibly the issue was simply at the feedly website end when syncing and they have resolved their issue ?

**Comment by elhennig** [comment]
Just tested, too. It works again for me.

**Comment by turbare** [comment]
Fixed for me as well, no change done on my end, seems to have fixed itself.

**Comment by Theyssen** [comment]
Fixed for me as well

**Comment by elhennig** [comment]
I see some strange behavior in 2.26.4 with FF 100 on Linux since yesterday: The mark as read only marks the latest article read, not all in the popup as before. Since there was no update of the feedly notifier it must be the firefox update or some config on the feedly API side.
