### ISSUE TITLE
Behavior in Firefox 100 (Linux/Windows)

### ISSUE THREAD

**Issue by elhennig** [olsh/Feedly-Notifier#212]
I see some strange behavior in 2.26.4 with FF 100 on Linux since yesterday: The mark as read only marks the latest article read, not all in the popup as before. Since there was no update of the feedly notifier it must be the firefox update or some config on the feedly API side.
Opening the feedly web site, marking all articles read there does not update the counter in the notifier addon, Also the popup sometimes does not open and it seems that the addon hangs

**Comment by elhennig** [comment]
Still not working with Firefox 101. Any update on this?

**Comment by olsh** [comment]
Hi @elhennig,

Have you tried to create a clean Firefox profile and test it again? 
Also, it would be helpful if you could provide errors from console.

**Comment by elhennig** [comment]
I do not see errors in the console that I could relate to this problem. Cleaning the profile is not an option for me at this point. There is some behavior with FF100+ with other addons to, that popups are closed and seem to hang for some time.

**Comment by olsh** [comment]
> Cleaning the profile is not an option for me at this point.

Just for a test.

I don't have a Linux machine to reproduce the issue. I didn't manage to reproduce the issue on a Windows machine.

**Comment by elhennig** [comment]
I guess it could also be related to some gtk libs on Linux in combination with FF 100+

**Comment by elhennig** [comment]
> > Cleaning the profile is not an option for me at this point.
> 
> Just for a test.
> 
> I don't have a Linux machine to reproduce the issue. I didn't manage to reproduce the issue on a Windows machine.

Maybe you can at least reproduce the behavior with not syncing to the feedly website on Windows. I could reproduce it on Windows.

**Comment by olsh** [comment]
I use the plugin myself on a daily basis and don't have the issue. Also, this is a pretty critical bug, but nobody has reported it yet.
Could you please provide the exact steps to reproduce? Also, please make sure you use the same account on the Feedly website and the extension.

**Comment by elhennig** [comment]
For the sync problem it seems that the problem was between Screen and the back of the chair :wink:  I feel a bit stupid :facepalm:  Apparently I was having one account to many...

So now, as I am doing it right, sync is working. Thanks for your hint! :+1: 
It only remains that the popup closes and hangs from time to time but this seems to be a FF problem on Linux as it affects other popups, too
