### ISSUE TITLE
"No Title" posts confuse the interface

### ISSUE THREAD

**Issue by victualsquid** [olsh/Feedly-Notifier#216]
When there are posts in my feed with no title they are displayed in this confusing way:

Here is a picture of the notifier drop-down.
https://i.imgur.com/s2zozHl.png

For the first one clicking the eye or dropdown symbol opens the page and marks it as read.
This is the post:
https://scarysigns.tumblr.com/post/687522464615546880
From this feed:
https://scarysigns.tumblr.com/rss

For the second one clicking the eye symbol opens a page that doesn't exist and marks the post as read. Clicking the dropdown symbol opens the same page and also opens the dropdown display. It also changes the way the post is displayed. Afterwards it looks more like the first post, but clicking the eye symbol only marks it as read without opening any pages.
It is this post:
https://askkrenko.tumblr.com/post/687236028198699008
From this feed:
http://askkrenko.tumblr.com/rss

My proposed solution: Just write "[no title]" instead of allowing an empty title in the display.

**Comment by victualsquid** [comment]
I don't actually care what is written in the fake title as long as things become consistent. 
I suggested "no title" because that is what feedly itself seems to use in their web-interface.

**Comment by olsh** [comment]
The issue was fixed in the 2.26.5 version. The version should be available soon.
Thanks 👍🏻
