### ISSUE TITLE
Annoying dot in the toolbar icon

### ISSUE THREAD

**Issue by ThiefMaster** [olsh/Feedly-Notifier#226]
![image](https://user-images.githubusercontent.com/179599/197514904-bbee54f4-b352-4553-8f75-96b74643cbb0.png)

This dot always shows up except when hovering the icon. It started showing up pretty recently - not sure if it's a problem with the latest firefox or the extension that's causing it.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 107.0b2

**Comment by olsh** [comment]
Hi @ThiefMaster 
It looks like it's a bug in FF.
https://discourse.mozilla.org/t/what-are-those-green-dots-under-some-addons-in-new-firefox-developer-edition-107/106797
