### ISSUE TITLE
Popup width 230px

### ISSUE THREAD

**Issue by Alukard-X** [olsh/Feedly-Notifier#247]
Chrome 116.0.5794.0
Popup width became 230px
![image](https://github.com/olsh/Feedly-Notifier/assets/8438102/1b404de5-3aff-4ee8-a942-44852ffc969c)

**Comment by olsh** [comment]
Hi @Alukard-X 
Is this the canary version? If it is, then sorry, but I don't have time to support beta/alpha versions.
But thank you for raising the issue and PR is welcome 🥇

**Comment by sek0n** [comment]
Just want to add that this has come to both Chrome and Edge Dev builds now. So it's probably headed towards beta/stable relatively soon.

I expect stuff like this on dev, so just to give a heads up.

Thanks for the great extension. ❤️

**Comment by andyharwoodnz** [comment]
I'm getting this in 2.29.0 straight from the chome store. Is there any workaround for this?

**Comment by olsh** [comment]
Hi @andyharwoodnz 
Please specify the browser version and OS.
I can't reproduce the issue on Chrome 114 on Windows 11.

**Comment by andyharwoodnz** [comment]
Hi @olsh 

Thanks foor getting back to me. I'm using Vivaldi browser and Feedly-Notifier 2.29.0

It updated at some point recently and since then the dropdown size is clipped:

![image](https://github.com/olsh/Feedly-Notifier/assets/44360598/059e6cc0-5ed3-43b6-94c6-e7ba3e721a7a)

Andy

**Comment by bonez565** [comment]
Same issue in chrome with the latest update. Version 116.0.5845.42 (Official Build) beta (64-bit)

![image](https://github.com/olsh/Feedly-Notifier/assets/11901899/eaed8559-0a3d-4310-8e94-a19a6550da56)

**Comment by olsh** [comment]
The fixed version 2.29.1 was published to stores.
Thank you @Alukard-X for the fix.

**Comment by andyharwoodnz** [comment]
Thank you! Much appeciated. Love this extension - I will never give up my legacy RSS :D
