### ISSUE TITLE
I logged into Feedly Notifier with the wrong account and now I can't change it

### ISSUE THREAD

**Issue by efekaradagli** [olsh/Feedly-Notifier#254]
Hey,

I've been a big fan of Feedly and Feedly Notifier for years. I first installed Feedly Notifier on my new computer, but accidentally signed in with my wrong Google account. I didn't have a feedly account opened with this email address before and now Notifier shows nothing and I can't login to another account.

Can you help me with this?

**Comment by efekaradagli** [comment]
+

I'm using the Feedly Notifier Chrome extension via Opera.

**Comment by olsh** [comment]
Hi @efekaradagli 

You can log out on the extension option page.

**Comment by efekaradagli** [comment]
Hi @olsh 

Thanks for your help. The log out sectioned appeared in the option page once but it isn't there any more so I am not able to log out. Here is a screen shot :

<img width="815" alt="Screenshot 2023-07-12 at 14 49 21" src="https://github.com/olsh/Feedly-Notifier/assets/74110074/da30384c-577b-4f18-af02-d258a6987e90">

**Comment by efekaradagli** [comment]
Okay I figured it out. I opened the manage extensions menu and turned the switch off and turned it back on. Then the extension restarted. 

Thank you
