### ISSUE TITLE
Outdated Opera extension

### ISSUE THREAD

**Issue by pentiak** [olsh/Feedly-Notifier#260]
**Describe the bug**
Opera extension is outdated vs other browsers. 
![image](https://github.com/olsh/Feedly-Notifier/assets/11030509/52201789-3ac5-4eab-9a33-7803ca839843)
Opera addons page lists version 2.28.0 when there is already 2.29.1 released.

**Expected behavior**
Opera addon service should provide the latest release of the addon.

**Comment by olsh** [comment]
Hi @pentiak 

After releasing the extension on the GitHub page, I always submit the updated version to all stores. 
If you don't see any extensions in the stores, they are in moderation. Here is the screencap from the Opera store.

<img width="1173" alt="image" src="https://github.com/olsh/Feedly-Notifier/assets/3613592/2814ea14-3d2d-41ff-bb33-a8ad5d311513">

**Comment by pentiak** [comment]
I see, thanks for the explanation. I switched to Chrome store for my Opera browser because of that. #263
