### ISSUE TITLE
Notification counter behavior is inconsistent/broken

### ISSUE THREAD

**Issue by thereddestdog** [olsh/Feedly-Notifier#283]
**Describe the bug**
Unread counter does not show when there are over 1,000 unread items, and is not showing correct counter (or at all) when there are a lot of unread items

**Expected behavior**
The counter should display 1k+ or the actual unread count if under 1,000

![image](https://github.com/user-attachments/assets/78958c83-5cc7-4aa1-b89b-a017280242fb)

![image](https://github.com/user-attachments/assets/ed27459d-5911-4425-87f8-9e963e3b0f61)

![image](https://github.com/user-attachments/assets/e94b0916-1975-4761-adad-05a7f5cdba7a)

![image](https://github.com/user-attachments/assets/36822e9f-494f-4bea-bf5a-9fee2d97a47a)

Running Firefox v129.0.2 64-bit on Windows 11 22H2

**Comment by olsh** [comment]
Well, I think the culprit is the option from your screencap
![image](https://github.com/user-attachments/assets/de60abab-2cfd-46d8-9c83-2e6009a05125)

**Comment by thereddestdog** [comment]
How should that option behave then? I'm expecting it to read in the current unread count when I click

**Comment by thereddestdog** [comment]
OK, so after that, when does it update with the correct count? Because I was seeing a 1, 2, or 3 displayed when I have 800+ items unread..  Oh maybe that low number is the amount of new items that came in since clicking reset... I think I follow how it is supposed to work now. 

And I only have one account, FYI

**Comment by olsh** [comment]
> OK, so after that, when does it update with the correct count?

It only counts new articles that were published after the counter was reset.

**Comment by thereddestdog** [comment]
OK makes sense, thank you!

**Comment by thereddestdog** [comment]
Hi @olsh now that I understand how that counter should work, I noticed that it does not accommodate counts of 1000+

Can you make this show 1k+ instead of three digits? Thanks!

![image](https://github.com/user-attachments/assets/c8f23ead-6bb2-4d64-94ca-af244f42c9f5)

**Comment by olsh** [comment]
You might want to consider opening a new issue for this. Unfortunately, I don't have time to address it right now, but a pull request would be appreciated.

Here's the code responsible for updating the badge.
https://github.com/olsh/Feedly-Notifier/blob/8b5329cd4438ee7b331a4f1380bc03fe42b0ec1f/src/scripts/core.js#L447-L462

**Comment by thereddestdog** [comment]
Thanks again for #[0da06b8](https://github.com/olsh/Feedly-Notifier/commit/0da06b88f2e2ece92d2ab4bf99451068b46cc447)
