### ISSUE TITLE
Feedly Notifier not refreshing the list correctly anymore

### ISSUE THREAD

**Issue by RejZoRSheep** [olsh/Feedly-Notifier#291]
**Describe the bug**
It's not updating/refreshing the list since recently. I mark entry as "Mark as read" and when I open the Feedly Notifier popup again, the same entries are there again that were marked as "Mark as read". I've tried logging into Feedly again, but it's still not refreshing.

**To Reproduce**
1. Open Feedly Notifier extension popup
2. Mark any entry on the feeds list as "Mark as read"
3. Close extension popup
4. Re-open Feedly Notifier and the "Mark as read" entries will still be there

**Expected behavior**
Entries marked as read should disappear from the list when marked.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2
 - Firefox
 - Version 132.0.2

**Comment by Thorketil** [comment]
Same bug also for me on
Desktop:

OS: Fedora Linux 40 (Workstation Edition)
Firefox
Version 132.0 (64 bits)

Tried to uninstall/reinstall the extension too, with no success, and I agree:
the problem seems to be on the Feedly side even though it happened concomitantly with the add-on update.

**Comment by vargn** [comment]
Same here, tried logging out and in again. But it rejects my login and redirects me to a "Server error" page: https://olsh.me/Feedly-Notifier/?error=server_error&error_description=Internal%20error&state

**Comment by vargn** [comment]
Confirmed working again, thanks!
