### ISSUE TITLE
Firefox 29 Linux Mint 17 Cinammon 

### ISSUE THREAD

**Issue by alienos** [olsh/Feedly-Notifier#39]
Icon displays the wrong feedly notifer firefox 29 linux mint 17 cinammon
![zrzut ekranu z 2014-06-04 14 13 51](https://cloud.githubusercontent.com/assets/7785010/3173168/2546d3bc-ebe2-11e3-8ee6-04ac0b40c631.png)

**Comment by olsh** [comment]
You can download the fixed version [here](https://addons.mozilla.org/en-US/firefox/addon/feedly-notifier/versions/?page=1#version-2.10.0).
Feel free to reopen the issue if bug still exists.
