### ISSUE TITLE
Brazillian Translation filename

### ISSUE THREAD

**Issue by mrfabers** [olsh/Feedly-Notifier#46]
Hi,

You can rename the "jquery.timeago.pt-br.js" file to "jquery.timeago.pt-BR.js" in the "timeago / locales"?

My Mac's file system (and my linux too) is case sensitive and always when you have an extension update I need to change manually.

Thank you

**Comment by olsh** [comment]
Thank you.
Closed by 070ea47dc0d5a10f0bb32d857a994f1002f068d3

**Comment by olsh** [comment]
Feel free to reopen the issue if you still have the problem.
