### ISSUE TITLE
Feature request: hide notifications

### ISSUE THREAD

**Issue by reicheltmediadesign** [olsh/Feedly-Notifier#56]
Hello,

currently I can choose to display notifications (or not), and how long they're visible. It would be nice if I can hold the mouse over the notification and the timeout stops.

For example, a new notification appears with a timeout of 10 seconds. After 10 seconds visibility, the notification will fade out. When I place the cursor above the notification, the countdown should stop until I remove the cursor.

Thanks

Regards
Philipp

**Comment by olsh** [comment]
I suppose that it's impossible to implement at this moment. Because web notifications do not support `onHover` event or something like that.
https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API#Notification_events

**Comment by olsh** [comment]
We don't have API to implement it.
