### ISSUE TITLE
Feature request: a button to add the feed of the currently visited website

### ISSUE THREAD

**Issue by Deuchnord** [olsh/Feedly-Notifier#57]
When the website the user's visiting offers an RSS/Atom feed, it would be great to give an option to add it in Feedly.

**Comment by olsh** [comment]
@Deuchnord thanks for the suggestion!
The official extension allows to do that.
https://chrome.google.com/webstore/detail/feedly-mini/ndhinffkekpekljifjkkkkkhopnjodja?hl=en

**Comment by Deuchnord** [comment]
Thanks for your answer, I hadn't see this extension existed. But looks like it doesn't work correctly: the bubble that should appear at the bottom right corner doesn't show up, so that I can't do anything. :(

**Comment by olsh** [comment]
Well, I don't use these kind of extensions, but you would try these ones.
https://chrome.google.com/webstore/detail/feedly-subscribe-button/gbbnddjfcllebfcnihfgmdplgaiejepc
https://chrome.google.com/webstore/detail/follow-feed-feedly/ccmkbgknapokcjabmiaimipiepgpgbco
