### ISSUE TITLE
Compatibility with multi-process Firefox

### ISSUE THREAD

**Issue by sschaef** [olsh/Feedly-Notifier#63]
This plugin is not yet fully compatible with multi-process Firefox.

https://www.arewee10syet.com/ marks it as `compatible-webextension` but inside of Firefox is is marked as not compatible:
![ff](https://cloud.githubusercontent.com/assets/488530/21293318/cc7bfb0c-c520-11e6-91e2-48ce2c99957b.png)

**Comment by Daktyl198** [comment]
This should happen in the next release, if Olsh finishes turning it into a WebExtension (which, by definition, are e10s compatible).

Don't know when that will be, though.

**Comment by olsh** [comment]
I've alredy converted it into a WebExtension. But it there is a bug with the panel, that's why I don't publish it to store.
I hope the bug will be fixed in FF 51. If you want to test it, there are instuctions how to build the extension.
https://github.com/olsh/Feedly-Notifier/blob/master/README.md
You have to specify `--browser firefox`.

**Comment by Keith94** [comment]
Hi @olsh 
I tested 2.12.1 in Firefox, but the options page has missing text for me, is it a known issue?

![firefox_2017-01-08_17-17-32](https://cloud.githubusercontent.com/assets/5490615/21755300/9a4535b6-d5c6-11e6-9eba-483beb1e6c06.png)

**Comment by olsh** [comment]
Hi @Keith94 
No, this is not a known issue.

Did you build it with this command?
`grunt sandbox --clientId=sandbox --clientSecret=R26NGS2Q9NAPSEJHCXM3 --browser firefox`

Please note that you have to specify the `build` folder when loading the extension locally.

**Comment by Keith94** [comment]
Oh sorry the trouble, I was not able to use `bower install` in the Git Shell, it seems I had to use `npm install -g bower` beforehand. Now it works.

Is there an easy way to package the files into an XPI for installing?

**Comment by olsh** [comment]
Not sure, but I suppose that there is no such way, because a WebExtension is just an archive.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension

**Comment by Daktyl198** [comment]
AFAIK, all you have to do is rename the .zip to .xpi and as long as you're running dev edition or nightly you should be able to install the extension.

**Comment by sschaef** [comment]
FF 51 has been released. Does the bug you were talking about still exist?

**Comment by olsh** [comment]
@sschaef 
Yes, the bug has been fixed in FF 51. 
I've published the WebExtensions version in AMO, it'll be available after AMO review.

**Comment by sschaef** [comment]
The most actual version is still 2.11.2: https://addons.mozilla.org/de/firefox/addon/feedly-notifier/ Did you publish somewhere else or are the newer versions still caught in review?

**Comment by olsh** [comment]
The addon didn't pass the review yesterday:

> This version didn't pass review because of the following problems:
> 1) This add-on is creating DOM nodes from HTML strings containing potentially unsanitized data, by assigning to innerHTML, jQuery.html, or through similar means. Aside from being inefficient, this is a major security risk. For more information, see https://developer.mozilla.org/en/XUL_School/DOM_Building_and_HTML_Insertion . Here are some examples that were discovered:
> - scripts/options.js line 84
> - popup.html line 71 you are using {{{ templates, which will render any html. As this html can come from a remote source, it would give that page access to the popup's context, which is not safe. Please sanitize the html received here, for example using a library like DOMPurify.

I'll be on vacation for 2 weeks without internet and PC, so sorry guys. I'll fix it only in the mid of March.

**Comment by nagato7** [comment]
Any update on e10s support?

**Comment by olsh** [comment]
The review is too slow.

![screenshot_032217_102130_am](https://cloud.githubusercontent.com/assets/3613592/24186439/52311414-0ee9-11e7-8a67-33bdcd2bfaa9.jpg)

**Comment by olsh** [comment]
The new version is on AMO.
Please let me know if everything OK with e10s.

**Comment by sschaef** [comment]
It works really great. Thanks for all of the work Oleg!
