### ISSUE TITLE
Layout glitch in Chrome

### ISSUE THREAD

**Issue by rojepp** [olsh/Feedly-Notifier#64]
Very often when I click the notifier icon in Chrome, it will render in the proper size, then immediately shrink to a tiny box, as can be seen in the gif below. 

![feedly](https://cloud.githubusercontent.com/assets/445888/21661919/00888834-d2d7-11e6-8b3f-46a7aaff105d.gif)

**Comment by olsh** [comment]
Thank you for the report.
I suppose it's a duplicate of https://github.com/olsh/Feedly-Notifier/issues/59

**Comment by rojepp** [comment]
Ah sorry!
