### ISSUE TITLE
Counter doesn't update immediately

### ISSUE THREAD

**Issue by Keith94** [olsh/Feedly-Notifier#66]
In Firefox, after I mark all items as read directly on the feedly.com website, the Feedly Notifier counter doesn't seem to update/reset by itself; it just shows the old value for a long period of time.

**Comment by olsh** [comment]
@Keith94 
Yes, this is a known issue, this feature was implemented only in the WebExtensions version.
Which I hope will be published soon.
Related issue https://github.com/olsh/Feedly-Notifier-Firefox/issues/136

**Comment by Keith94** [comment]
I see, thanks for confirming.
For a workaround I simply use the option "Reset counter when button clicked".

**Comment by Keith94** [comment]
2.12.2 is mentioned in the Firefox changelog, but not on AMO yet. Is something blocking it?

**Comment by olsh** [comment]
@Keith94 
Yes, AMO reviewers. :) I hope it'll be available soon.

**Comment by olsh** [comment]
@Keith94 
The addon was just approved and it's available on AMO. 
Please let me know if everything works as expected.

**Comment by Keith94** [comment]
Issue is fixed. :) Thanks

**Comment by olsh** [comment]
Emm, probably it was only in FF version. Please open a new issue if there is no such option, I'll implement it.
