### ISSUE TITLE
Stop working in Chrome

### ISSUE THREAD

**Issue by morawcik** [olsh/Feedly-Notifier#67]
Hi
Today Feedly Notifier stop working in Chrome. Its show count and news but don't mark it as read. Reinstall not help.

**Comment by olsh** [comment]
Hi
It can be reproduced on any feeds or only on specific ones?

**Comment by morawcik** [comment]
Its wont work with all my feeds (10 pages + 1 disqus channel)

**Comment by olsh** [comment]
Could you please check background page errors on the page chrome://extensions/?

**Comment by morawcik** [comment]
"https://cloud.feedly.com/v3/markers?av=c2.12.2 Failed to load resource: the server responded with a status of 405 ()"

**Comment by morawcik** [comment]
It seems that works again

**Comment by olsh** [comment]
Hmm, strange. Probably some issue on Feedly side.

https://developer.feedly.com/v3/markers/#mark-one-or-multiple-articles-as-read
According to the docs, it should be a POST request and the extension use POST to mark feeds as read.

**Comment by olsh** [comment]
@morawcik 
Can we close the issue out?

**Comment by morawcik** [comment]
Oh, yes. Sorry.
