### ISSUE TITLE
Add 'gray color if no unread' to Firefox version

### ISSUE THREAD

**Issue by Keith94** [olsh/Feedly-Notifier#69]
![image](https://cloud.githubusercontent.com/assets/5490615/24731223/71f29a90-1a1d-11e7-9722-ef5375e1ff35.png)

**Comment by Keith94** [comment]
I have noticed the icon sometimes doesn't change to gray, or it quickly flickers to gray and back to green after marking items as read. Can you check if there's some bugs?

**Comment by olsh** [comment]
I'll take a look at it. Please let me know if you find steps to reproduce.
