### ISSUE TITLE
[2.13.3, Firefox] "Open Feedly site on icon click" option now broken

### ISSUE THREAD

**Issue by lucidfox** [olsh/Feedly-Notifier#71]
The "Open Feedly site on icon click (don't show popup)" option has stopped working. Setting it has no effect, and on reopening the options page, the checkbox is reset to unset state.

**Comment by olsh** [comment]
@lucidfox please specify browser.

**Comment by lucidfox** [comment]
Firefox 52.0.2, Linux 64-bit.

**Comment by olsh** [comment]
Hmm, it works on windows, probably it's a Linux specific bug.
I don't have Linux installed now so I can't test it. Did you see any errors in FF console (ctrl + shift + J)?

**Comment by lucidfox** [comment]
Nope, no errors in the console. Clicking and unclicking the checkbox just doesn't seem to do anything besides enabling and disabling the rest of the Popup option group.

**Comment by lucidfox** [comment]
Never mind, I'm stupid. I didn't realize there was a Save button.
It seems something wiped out my options (perhaps the extension update?) and I forgot one needed to click Save to apply settings.
Closing the issue.

**Comment by olsh** [comment]
@lucidfox 
Yeah, there was a big update for FF version. We migrated it to WebExtensions so yes, your settings were set to defaults. We probably change the options page in the next releases to avoid this kind of confusion.
