### ISSUE TITLE
Notifications on desktop doesn't work

### ISSUE THREAD

**Issue by Alain1978** [olsh/Feedly-Notifier#72]
Since the update of 2.13.3 on Firefox, the notifications on desktop doesn't work. I cheked the rule "make a noise ...", I hear the sound but I don't see any popup ! I'm on Firefox 52.0.2 64 bits windows 10. Thank you for your addon who is very useful especially now in wb version, Alain.

**Comment by olsh** [comment]
Hi @Alain1978 ,
Thanks for the feedback. 
Could you please set option "Max notifications count at once" to "1" and test it again?

**Comment by Alain1978** [comment]
Hello, I tried your option but no changes, the notification doesn't appeared but the sound  with yes. I tryed something else,  I desactivated ublock but again with the same result.

**Comment by olsh** [comment]
@Alain1978 
Thanks. Probably there are some differences between Chrome and FF API. Will fix it.

**Comment by Alain1978** [comment]
Maybe, thx and sorry for my bad english.
