### ISSUE TITLE
Popup shows content only on hover

### ISSUE THREAD

**Issue by ThiefMaster** [olsh/Feedly-Notifier#73]
Happens in Firefox (52.0.2 on Win7) since today.

![feedlywtf](https://cloud.githubusercontent.com/assets/179599/24824250/333f08c8-1c08-11e7-8cde-cee8514e4632.png)

**Comment by olsh** [comment]
Hmm, looks strange.
Can't reproduce it, have you tried to use a clean FF profile?

**Comment by ThiefMaster** [comment]
Doesn't happen on another PC so I guess it's related to something in the profile.
Starting with a new profile if obviously not a good solution except to test it.

Any pointers how to track down what's causing it besides selectively disabling other extensions? My first thought was a userContent/userChrome css but I don't have either (except some userContent.css entry for an unrelated site)

**Comment by olsh** [comment]
I'd suggest to inspect the panel, but Firefox dev tools can't do that.
Maybe you can find something suspicion in the file?
https://github.com/olsh/Feedly-Notifier/blob/master/src/styles/style.css

**Comment by ThiefMaster** [comment]
apparently firefox [can debug webextensions now](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging) :) 

It's extremely weird: If I set `background-color: #fff` on `.item` it works fine. Somehow the text etc in there is invisible if the element has no background color. This is also why it showed up fine on hover - `.item:hover` already has a background color.

**Comment by olsh** [comment]
Whoa, didn't know that it allows to inspect the panel.
Yeah, that's really strange, will add this workaround for now.
Let me know if you find something else.

Thank, you.

**Comment by olsh** [comment]
Fix in https://github.com/olsh/Feedly-Notifier/commit/f0ef0302520ab2619e77950dab5e4325db0a793d
