### ISSUE TITLE
Mark all as read should mark ALL as read

### ISSUE THREAD

**Issue by Erythros** [olsh/Feedly-Notifier#77]
First time I opened the extension I had 9000 unread stories. Clicking "mark all as read" would mark only the first 20 items (first page) as read leaving me with 8980 unread stories. 

With the current behavior, I would have to click 450 times "mark all as read" so I can get to the present day.

Expected behavior: "mark all as read" should mark ALL items as read.

**Comment by olsh** [comment]
Thanks for the feedback.
Well, you are right, but it's too late to change the behavior, because many users don't expect it. 
Moreover, the purpose of the extension is notify, not to copy the entire site functionality.

Please let me know what do you think.

**Comment by olsh** [comment]
Feel free to reopen the issue.
