### ISSUE TITLE
Во всплывающем окне не показывает тело сообщения

### ISSUE THREAD

**Issue by itcareerwork** [olsh/Feedly-Notifier#80]
Заранее прошу прощения, что не на английском

После обновления на новую версию перестал показывать тело новости под заголовком. 
В настройках само собой  выставлено "Показывать полное содержание статьи при раскрытии новости (если возможно)" и "Раскрывать все новости при открытии всплывающего окна".      
Прикрепляю скрин.  Происходит это так: 
1) При открытии окна новость не показывается, при этом маркер (галочка) развернута. (1 на скрине)
2) При принудительном сворачивании-разворачивании конкретная новость показывается как нужно (2 на скрине)

Windows 7, Opera
Данные: 
Информация о версии
Версия:	44.0.2510.1449 (PGO) - Используется обновленная версия Opera
Система:	Windows 7 32-bit
Идентификация браузера
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36 OPR/44.0.2510.1449
Feedly Notifier
Версия 2.14.0, автор: olshevchenko
![feedly](https://cloud.githubusercontent.com/assets/20427817/25431679/06ecd3b2-2a9b-11e7-974c-d6d2efee4291.jpg)

**Comment by olsh** [comment]
Добрый день, спасибо что написали. 👍 
В курсе этой проблемы, надеюсь что скоро исправлю.

https://github.com/olsh/Feedly-Notifier/issues/75

**Comment by itcareerwork** [comment]
Вам спасибо за такую полезность :)
