### ISSUE TITLE
Chrome Optional Permissions for notifications

### ISSUE THREAD

**Issue by WORMSS** [olsh/Feedly-Notifier#81]
You may want to check out https://developer.chrome.com/extensions/permissions

I almost didn't allow the Feedly chrome extension to update itself and would have been forced to remove because I didn't want to be spammed with lots of notifications and chrome doesn't allow me to run an old version of an extension. It wasn't until I seen this issue tracker I found that it was optional.. But I thought, why is it asking me for permission if it's turned off.. I am guessing you guys didn't know about this.

```javascript
document.querySelector('#enableDesktopNotifications').addEventListener('click', function(event) {
        // Permissions must be requested from inside a user gesture, like a button's
        // click handler.
        chrome.permissions.request({
          permissions: ['notifications']
        }, function(granted) {
          // The callback argument will be true if the user granted the permissions.
          if (granted) {
            doSomething();
          } else {
            doSomethingElse();
          }
        });
      });
```

**Comment by inequation** [comment]
A concern about the permission for reading & writing on every website brought me to this issue. Why is it even required?

**Comment by Palatosino** [comment]
Here #78  is the reason. I was looking for some explanation too.

I didn't know if Feedly Notifier is now malware or can be malware in some update.

**Comment by anotherjames** [comment]
Thanks! :-)

**Comment by olsh** [comment]
You're welcome :)
