### ISSUE TITLE
 2.14.1 requires new permissions

### ISSUE THREAD

**Issue by schliflo** [olsh/Feedly-Notifier#82]
Chrome tells me that  2.14.1 requires new permissions, including "Read and change all data on websites you visit" which seems a bit odd. Can you specify why that is the case and for what feature this change is needed?
![screen shot 2017-04-27 at 13 06 22](https://cloud.githubusercontent.com/assets/9881672/25480730/62f63fa4-2b4a-11e7-82bb-14a8c69f8c56.png)

**Comment by olsh** [comment]
Thanks for the feedback.
It's fixed already, the new version will be on store in ~30 minutes.

More info:
https://github.com/olsh/Feedly-Notifier/issues/81
https://github.com/olsh/Feedly-Notifier/pull/78

**Comment by olsh** [comment]
The fixed version was published.
Feel free to reopen the issue.

**Comment by schliflo** [comment]
Thx for the info. Can confirm the permission is gone in 2.14.2  - although I had to remove the extension and re-install it in order to get rid of the chrome notification.
