### ISSUE TITLE
Unable to load since Chrome update

### ISSUE THREAD

**Issue by BArcher001** [olsh/Feedly-Notifier#83]
Hi everyone,

Since the recent update of Chrome I've been unable to get Feedly Notifier to work - Chrome is giving an error of: NET::ERR_CERT_WEAK_SIGNATURE_ALGORITHM

Any idea how this can be resolved?

Thank you!

**Comment by olsh** [comment]
Hi @BArcher001 ,
Which OS are you using?

**Comment by BArcher001** [comment]
Thanks for the quick reply. Using Windows 10.

**Comment by olsh** [comment]
That's strange, Feedly API uses SHA256withRSA certificate. 
https://www.sslshopper.com/ssl-checker.html#hostname=https://cloud.feedly.com/v3/streams/

And I'm on windows 10 and the latest Chrome too.

You can disable "Use HTTPS" in the extension options, but all requests to Feedly API will be unsecure.
Also, please check the forum
https://productforums.google.com/forum/#!topic/chrome/aZCjPYqdtHk;context-place=forum/chrome

**Comment by olsh** [comment]
Closing this out, feel free to reopen.
