### ISSUE TITLE
"Mark as read" icon moves the list always to the beginning

### ISSUE THREAD

**Issue by LukasThyWalls** [olsh/Feedly-Notifier#85]
**How to reproduce**:

- Open Feedly Notifier
- You need a lot of feed entries, at least a few to have the scrollbar 
- Scroll down in the Feedly Notifier and select an entry what isn't any of the first ones.
- When you click a "Mark as read" icon in that entry, it does, and the Feedly Notifier screen goes up to the beginning, and you need to go down again to see what you are seeing before.

It's annoying when you are inspecting the feed entries, but you don't want to mark the first ones for see later, and with every "Mark as read" you do, it scroll up automatically and you need to scroll down every time.

**What is supposed to do**:

- It doesn't scroll up when you click in "Mark as read", keeping the position on the list and only "deleting" that entry from the list.

**Info**:

- Firefox 53.0.2
- Feedly Notifier 2.14.2

**Comment by olsh** [comment]
Hey @LukasThyWalls , thanks for the detailed description. 👍 
There is a bug in Bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=1324499

**Comment by ThiefMaster** [comment]
Could this be worked around somehow in case it takes a decade to be fixed in firefox (wouldn't be the first time a small but stays open that long ;x)

**Comment by olsh** [comment]
It seems that the bug was fixed in FF 57.
