### ISSUE TITLE
not getting notifications

### ISSUE THREAD

**Issue by Imold** [olsh/Feedly-Notifier#88]
I'm not getting Desktop notification. I'm running Waterfox 53.0.1 (64-bit) on windows 10.

**Comment by olsh** [comment]
Hey @Imold ,

Thanks for letting me know, I've just published a new version (2.15.0) to AMO, it's under review now.
Please try it when it'll be available and let me know if the problem is fixed.

**Comment by Imold** [comment]
It's working in the new version.
