### ISSUE TITLE
Can't access feeds

### ISSUE THREAD

**Issue by QXD-me** [olsh/Feedly-Notifier#90]
Hi

I'm having an issue where I can't access the feeds through the extension, but I can through the Feedly website. The extension shows a grey icon, and when I click it I just see the spinning wheel. I have tried uninstalling and reinstalling the extension with no luck. It started doing it yesterday (or maybe the day before), and I think it briefly started working again yesterday evening before going back to not working.

Any ideas? Anything I can do to help diagnose the cause?

I'm on Windows 10 (64bit), Firefox stable (53.03 32bit).

**Comment by olsh** [comment]
Hey @QXD-me ,

Have you tried to create a clean FF profile, just for test?

> Anything I can do to help diagnose the cause?

Close all tabs and disable all addons except FN. Reopen the browser, reproduce the bug and hit `ctrl + shift + J`, if there are any errors in the console, let me know.

**Comment by QXD-me** [comment]
Thanks for the help @olsh . Clean profile worked which led me to figure it out.

It seems that another extension, uMatrix, is interfering somehow. After disabling it I managed to log in and re-enabling umatrix seems to cause some issues. (In case anyone else has the same issue I have added the following line to the rules "* cloud.feedly.com xhr allow" which seems to sort the problem). I'm not sure why this only became an issue recently, as my setup hasn't changed.

Possibly not useful anymore, but when I re-enabled the Feedly Notifier extension with the console open I got the following
```
1496341745549	addons.webextension.jid1-BOjn8b0IM7kH2w@jetpack	WARN	Loading extension 'jid1-BOjn8b0IM7kH2w@jetpack': Reading manifest: Error processing optional_permissions: An unexpected property was found in the WebExtension manifest.
1496341745549	addons.webextension.jid1-BOjn8b0IM7kH2w@jetpack	WARN	Loading extension 'jid1-BOjn8b0IM7kH2w@jetpack': Reading manifest: Error processing gecko: An unexpected property was found in the WebExtension manifest.
1496341745565	addons.webextension.jid1-BOjn8b0IM7kH2w@jetpack	WARN	Please specify whether you want browser_style or not in your browser_action options.
In add-on jid1-BOjn8b0IM7kH2w@jetpack, attempting to use listener "notifications.onButtonClicked", which is unimplemented.
```

**Comment by olsh** [comment]
@QXD-me thanks for the investigation! 🥇
