### ISSUE TITLE
Feature request: add option 'close popup after selecting Feedly website'

### ISSUE THREAD

**Issue by GAJansen** [olsh/Feedly-Notifier#91]
When I have a lot of new feeds, I use the FN popup to briefly check these, but if I find something interesting, I choose to manage/read these on the Feedly website rather than using the FN-popup. Selecting 'Feedly website' opens the website, but leaves the popup open, so one additional click is needed to close the popup.
As I assume that (many) users that will go to the Feedly website want to use the website instead of the FN-popup, my suggestion is:

add an option to FN: close popup after selecting 'Feedly website'.

I am aware of the option 'Open Feedly site on icon click (don't show popup)' but that is too much, I want to be able to open the popup too.

**Comment by olsh** [comment]
Hi @GAJansen,
I suppose you are using Firefox? 
I think we don't need an option for this, this should be the default behavior.

**Comment by GAJansen** [comment]
Hi @olsh,
I use several browsers on different OS's (Ubuntu 16.04, Lubuntu 17.04 , Win7, Win10 (32-bit, 64-bit)).
I agree that the default behaviour should be: close popup after selecting feedly website.
This indeed is the default already in Opera, Chromium, Chrome.
But it is currently not the default in Firefox, Vivaldi (this is remarkable, as I thought Vivaldi is a fork of Opera)

**Comment by olsh** [comment]
Thanks for the investigation! 👍 

> close popup after selecting feedly website.

Will make this as the default behavior for all browsers.

**Comment by olsh** [comment]
Fixed in a4e9d2a4c2efe632e262c646018406a7de1fe6fc

**Comment by GAJansen** [comment]
Thanks for the quick fix, Oleg!
