### ISSUE TITLE
Unread badge not showing up for the past few days

### ISSUE THREAD

**Issue by ramenchef** [olsh/Feedly-Notifier#92]
Since 1 or 2 days ago, the feedly notifier icon is no longer showing a badge with the number of unread articles. I have attempted to log out and relog back into feedly to try and fix it.

**Comment by olsh** [comment]
Hi @ramenchef , which browser are you using?

**Comment by ramenchef** [comment]
Woops, I should probably include that. I am in Win10 Pro 64 bit. This is happening on Chrome 64bit both 58 and 59 stable.

**Comment by olsh** [comment]
Could you please enable developer mode on the page `chrome://extensions` and check if there are errors in the background page?

**Comment by cyberrufus** [comment]
Same issue with an "unable to load counter" error. Windows 10 x64 Chrome developmental build.

**Comment by cyberrufus** [comment]
Another error I'm receiving:
`Error in response to storage.get: ReferenceError: parameters is not defined`

**Comment by cyberrufus** [comment]
Stack trace:
scripts/core.js:422 (Object.callback)
scripts/core.js:416 (updateCounter)
scripts/core.js:151 (chrome.webRequest.onCompleted.addListener.urls)
(I've disabled that feature)

**Comment by olsh** [comment]
@cyberrufus @ramenchef 

Did you enable the option `Reset counter when extension button clicked`? 
It seems I manage to reproduce the issue.

**Comment by cyberrufus** [comment]
Yes; most recent error with trace:
Error in response to storage.get: ReferenceError: parameters is not defined
Stack Trace:
scripts/core.js:422 (Object.callback)
scripts/core.js:416 (updateCounter)

**Comment by olsh** [comment]
Ok, thanks for the info. 👍 
I've just pushed a new version to store (2.15.1). I hope it'll be available shortly, please let me know if the issue still exists in the version.

**Comment by cyberrufus** [comment]
Issue appears resolved in the new version (2.15.1). Thanks for the quick response!

**Comment by olsh** [comment]
@cyberrufus thanks for the feedback! 👍 

@ramenchef please, let me know if the fix works for you too.

**Comment by ramenchef** [comment]
I believe I had that option checked before and it's working now. Thanks!
