### ISSUE TITLE
Notifier is no longer clearing badge count

### ISSUE THREAD

**Issue by Nos402** [olsh/Feedly-Notifier#93]
My Chrome notifier extension is no longer clearing the badge count when I mark all as read. If I click it, there are no articles in the list, but the last badge number remains.

**Comment by olsh** [comment]
Hi @Nos402, have you tried to re-login?

**Comment by Nos402** [comment]
I had not. I had restarted Chrome twice to get rid of the notifications before. Today, all seems to be working fine.

**Comment by WORMSS** [comment]
I am getting this today, sadly a restart is not helping it.. I am getting errors..
![image](https://user-images.githubusercontent.com/1384537/27120822-ef5a1e40-50dc-11e7-8d9c-4cf78abdbcab.png)
A restart doesn't seem to help. I am able to log in to the feedly page myself.

**Comment by olsh** [comment]
Hi @WORMSS ,
Could you please set a breakpoint here https://github.com/olsh/Feedly-Notifier/blob/master/src/scripts/core.js#L864-L888 and check if you get an access token on 884 line?
This code is executed on login.

Thanks,
Oleg.

**Comment by olsh** [comment]
I'm clothing the issue out.
Feel free reopen it if you still experience the issue.
