### ISSUE TITLE
Notifier is not working 

### ISSUE THREAD

**Issue by morvamorva** [olsh/Feedly-Notifier#94]
Hi, this morning the notifier stopped working completely. 

It is not fetching and whenever I click on it, it says “no unread articles” even though it shows I have 115 new articles (see screenshot)
![notifier screenshot](https://user-images.githubusercontent.com/29438937/27146659-0f7cc72e-5108-11e7-8f5b-e5b1a8119c56.PNG)

I went on the feedly website and checked my articles and the extension did not update after I checked my notifications on the site and it is not alerting me of new content either.  

I tried to log out and back in, but once I log out there is no option to log back in. Though, the widget looks the same with the same 115 notifications and the same message. I have restarted my computer, browser. etc. I don't think the problem is on my side.

**Comment by olsh** [comment]
Hi @morvamorva, thanks for letting me know.
There was an issue with logout. Just fixed it and pushed a new version to store, will be available in ~30 minutes.

Please try to log out and check if the issue is solved.

**Comment by morvamorva** [comment]
It works now, I had to remove it and reinstall it. Thank you very much for your quick attention!

**Comment by maualberti** [comment]
Same problem: always "“no unread articles” even though it shows I have new articles
