### ISSUE TITLE
Feature Request: keywords filter for individual feeds

### ISSUE THREAD

**Issue by xzyguo** [olsh/Feedly-Notifier#95]

**Comment by olsh** [comment]
Hi @xzyguo ,

Could you please explain more detail? Is there such feature on Feedly.com?

**Comment by xzyguo** [comment]
Hi @olsh 
Perhaps no such feature on Feedly.com. I don't use feedly directly too much, not that familiar.
Like I subscribed an Android system changelog RSS, and I set a filter keyword 'security', then automatically mark all messages without 'security' in title as read.

**Comment by morvamorva** [comment]
@olsh there actually is a keywords filter feature now, they rolled it out last week I think. They call it "mute filters". Feedly notifier still notifies me on the things I have filtered out, so I think an update would be useful.

**Comment by olsh** [comment]
Hi @morvamorva
Thanks for the info. Just for the reference: https://blog.feedly.com/mute-filters/

1. It seems like there is no API for the feature at the moment: https://developer.feedly.com/
2. The feature is available only for Pro users. I don't have Pro plan, so PRs are welcome. :)

**Comment by morvamorva** [comment]
Hey @olsh 
I am happy to help, but am not a developer. Let me know how I can help.

**Comment by olsh** [comment]
Hey @morvamorva 

> I don't have Pro plan, so PRs are welcome. :)

This was addressed to everybody. :)

> Let me know how I can help.

I think we have nothing to do at the moment, we need API for the feature at least.

**Comment by clavat** [comment]
Hi,

Yes it could be very nice to have filter in your extension, that automatic mark as read every news that match the filter.
For me I search for a popularity filter, Feedly can do it in Pro plan, but i guess with a small PR it's possible to mark as read every news with low popularity ?

@olsh is it possible ?

**Comment by olsh** [comment]
Hi @clavat 

Well, probably it's possible to implement a workaround for the specific filter case(low popularity), but we need to load _all articles_ (some users can have thousands of unread articles) from time to time to check the popularity and mark them as read. 
Moreover, the popularity is not a constant value, don't know how Feedly handle this in their filters.

Please, correct me if I'm wrong.
