### ISSUE TITLE
 'Click on articles action' moves the list always to the beginning

### ISSUE THREAD

**Issue by cialu** [olsh/Feedly-Notifier#97]
Probably, related to  ["Mark as read" icon moves the list always to the beginning #85](https://github.com/olsh/Feedly-Notifier/issues/85)
issue opened by @LukasThyWalls on 11 May

**How to reproduce:**
- Open Feedly Notifier
- You need a lot of feed entries, at least a few to have the scrollbar
- Scroll down in the Feedly Notifier and select an entry
- Click on that entry, a new panel with the article is opened, and the Feedly Notifier screen goes up to the beginning, and you need to go down again to see what you are seeing before

It's annoying because it scroll up automatically and you need to scroll down every time.

**What is supposed to do:**

- It doesn't scroll up when you click the articles, keeping the position on the list and only "deleting" that entry from the list.

**Info:**
- Firefox 53.0
- Feedly Notifier 2.15.2
- Ubuntu 17.04
- Fedora 26 beta

**Comment by olsh** [comment]
Hi @cialu 
Thanks for the report. 👍 
Yes, it's related to #85 
The scroll goes up on every DOM modification (this is an SDK bug).

Please vote for the issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1324499
